name: aps_8id_bluesky_2024_2

# download:
#   wget https://raw.githubusercontent.com/BCDA-APS/bluesky_training/main/bluesky/environments/environment_2024_2.yml
# create:
#   conda env create --force -n bluesky_2024_2 -f ./environment_2024_2.yml --solver=libmamba
# activate:
#   conda activate bluesky_2024_2

# Add/revise environment variable for default bluesky environment.
# Add to ~/.bash_aliases (or if that does not exist, ~/.bashrc).
# export BLUESKY_CONDA_ENV=bluesky_2024_2

# For more advice about bash environment variables, see:
# https://github.com/BCDA-APS/bluesky_training/blob/main/bluesky/environments/admin/bluesky.md#bash-environment-variables

channels:
  - apsu
  - conda-forge
  - aps-anl-tag
  - defaults

dependencies:

  # --- Python core packages
  - python >=3.10
  - ipython
  - jupyter
  - jupyterlab
  - notebook
  - pip
  - psutil

  # --- testing and quality assurance
  - black
  - flake8
  - pylint
  - pytest
  - pytest-notebook
  - ruff

  # --- Qt
  - pyqt =5
  - qt =5

  # --- general support packages
  - apischema
  - bitshuffle
  - epics-base >=7.0.5
  - h5py
  - hdf5plugin
  - httpie
  - imagecodecs-lite
  - ipympl
  - lxml
  - pandas
  - pint
  - pyEpics >=3.5.0
  - pymongo
  - pysumreg
  - scikit-image
  - xlrd

  # --- Bluesky framework packages
  - apstools
  - area-detector-handlers
  - bluesky >=1.8.1,!=1.11.0
  - bluesky-httpserver
  - bluesky-kafka
  - bluesky-live
  - bluesky-queueserver
  - bluesky-queueserver-api
  - bluesky-widgets
  - databroker-pack
  - databroker =1.2
  - hklpy >=1.0.3  # --- linux-64
  - httpx >=0.14  # issue #75
  - ophyd >=1.7
  - pydm
  - tiled
  - xarray !=2022.6.0  # incompatible with numpy=1.20

  # --- user-requested packages
  - nexpy
  - punx
  - pvapy
  - pvview
  - pymca
  - pyRestTable
  - spec2nexus
  - xrayutilities

  # --- packaging and publishing
  - conda-build
  - coverage
  - mamba
  - micromamba
  - myst-parser
  - nbsphinx
  - pydata-sphinx-theme
  - pygithub
  - sphinx
  - sphinx-design
  - sphinx-tabs
  - sphinxcontrib-napoleon
  - twine
  - versioneer
  - aps-dm-api >=5   # linux-64  osx-64


  - pip:
    - apsbss  # only works on APS subnet
    - ophyd-registry
    - happi
    - tiled[all]
    - https://github.com/BCDA-APS/adl2pydm/archive/main.zip
